-- SET SESSION sql_mode = '';

LOAD DATA LOW_PRIORITY LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\CyberSource\\CS_Transactions_20190801.csv' 
REPLACE INTO TABLE `rcbill_my`.`cs_transactions` CHARACTER SET UTF8 FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\n' 
IGNORE 1 LINES 
(
@cybersourcemerchantid,
@dateandtime,
@requestid,
@merchantrefno,
-- @clientcode,
-- @paymentdate,
@lastname,
@firstname,
@emailaddress,
@paymentamount,
@paymentcurrency,
@accountsuffix,
@applications,
@accounttype,
@digitalpaymentmethod,
@transrefno,
@authind,
@partorigtranid,
@deviceid,
@terminalserialno,
@processor,
@tokenid,
@busapplicationid,
@terminalid,
@patranid,
@xid,
@merchantdefineddata1,
@merchantdefineddata2,
@merchantdefineddata3,
@merchantdefineddata4,
@clientuser,
@salesslipno,
@authcode,
@acqmerchantid,
@jccaterminalid,
@billingaddress1,
@billingcity,
@billingstate,
@billingpostalcode,
@billingphoneno,
@ipaddress,
@billingcountry,
@shipfirstname,
@shiplastname,
@shipaddress1,
@shipcity,
@shipstate,
@shipcountry,
@shippostalcode,
@shipphoneno,
@customerid,
@clientapplication

) 
set 
  
CYBERSOURCEMERCHANTID=@cybersourcemerchantid ,
DATEANDTIME=str_to_date(@dateandtime,'%b %d %Y %h:%i:%s %p GST') ,
REQUESTID=@requestid , 
MERCHANTREFNO=@merchantrefno,
CLIENTCODE=upper(trim(SUBSTRING_INDEX(@merchantrefno,'/',1))),
PAYMENTDATE=str_to_date(SUBSTRING_INDEX(@merchantrefno,'/',-1),'%d.%m.%Y %H:%i:%s'),
LASTNAME=upper(trim(@lastname)),
FIRSTNAME=upper(trim(@firstname)),
EMAILADDRESS=trim(@emailaddress),
PAYMENTAMOUNT=@paymentamount ,
PAYMENTCURRENCY=@paymentcurrency,
ACCOUNTSUFFIX=@accountsuffix,
APPLICATIONS=@applications,
ACCOUNTTYPE=@accounttype,
DIGITALPAYMENTMETHOD=@digitalpaymentmethod,
TRANSREFNO=@transrefno,
AUTHIND=@authind,
PARTORIGTRANID=@partorigtranid,
DEVICEID=@deviceid,
TERMINALSERIALNO=@terminalserialno,
PROCESSOR=@processor,
TOKENID=@tokenid,
BUSAPPLICATIONID=@busapplicationid,
TERMINALID=@terminalid,
PATRANID=@patranid,
XID=@xid,
MerchantDefinedData1=@merchantdefineddata1,
MerchantDefinedData2=@merchantdefineddata2,
MerchantDefinedData3=@merchantdefineddata3,
MerchantDefinedData4=@merchantdefineddata4,
CLIENTUSER=@clientuser,
SALESSLIPNO=@salesslipno,
AUTHCODE=@authcode,
ACQMERCHANTID=@acqmerchantid,
JCCATERMINALID=@jccaterminalid,
BILLINGADDRESS1=@billingaddress1,
BILLINGCITY=@billingcity,
BILLINGSTATE=@billingstate,
BILLINGPOSTALCODE=@billingpostalcode,
BILLINGPHONENO=@billingphoneno,
IPADDRESS=@ipaddress,
BILLINGCOUNTRY=@billingcountry,
SHIPFIRSTNAME=@shipfirstname,
SHIPLASTNAME=@shiplastname,
SHIPADDRESS1=@shipaddress1,
SHIPCITY=@shipcity,
SHIPSTATE=@shipstate,
SHIPCOUNTRY=@shipcountry,
SHIPPOSTALCODE=@shippostalcode,
SHIPPHONENO=@shipphoneno,
CUSTOMERID=@customerid,
CLIENTAPPLICATION=@clientapplication,
INSERTEDON=now()

;

select * from rcbill_my.cs_transactions;

