use rcbill_my;

drop table if exists dailysales;

CREATE TABLE `dailysales` (
`SALESCHANNEL` varchar(255) DEFAULT NULL ,
`SALESCENTER` varchar(255) DEFAULT NULL ,
`CREATEDBY` varchar(255) DEFAULT NULL ,
`REGION` varchar(255) DEFAULT NULL ,
`ORDERSERVICE` varchar(255) DEFAULT NULL ,
`MODELTYPE` varchar(255) DEFAULT NULL ,
`ORDERTYPE` varchar(255) DEFAULT NULL ,
`STATE` varchar(255) DEFAULT NULL ,
`ORDERID` int(11) DEFAULT NULL ,
`ORDERDATE` datetime DEFAULT NULL ,
`CLIENTCODE` varchar(255) DEFAULT NULL ,
`CLIENTCLASS` varchar(255) DEFAULT NULL ,
`CONTRACT` varchar(255) DEFAULT NULL ,
`CONTRACTTYPE` varchar(255) DEFAULT NULL ,
`SERVICE` varchar(255) DEFAULT NULL ,
`SERVICETYPE` varchar(255) DEFAULT NULL ,
`COST` decimal(12,5) DEFAULT NULL ,
`PRICE` decimal(12,5) DEFAULT NULL ,
`NUM` smallint DEFAULT NULL ,
`ORIGINALCONTRACT` varchar(255) DEFAULT NULL ,
`ORIGINALSERVICE` varchar(255) DEFAULT NULL ,
`ORIGINALSERVICETYPE` varchar(255) DEFAULT NULL ,
-- `ORIGINALCOST` decimal(12,5) DEFAULT NULL ,
`ORIGINALPRICE` decimal(12,5) DEFAULT NULL ,

-- NEW FIELDS
`CLEANORIGCOST` decimal(12,5) DEFAULT NULL ,
`CLEANORIGPRICE` decimal(12,5) DEFAULT NULL ,

`INSERTEDON` datetime DEFAULT NULL 



) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE INDEX IDXDS1
ON dailysales (ClientCode);

CREATE INDEX IDXDS2
ON dailysales (Contract);

SHOW INDEX FROM dailysales;