SELECT `COLUMN_NAME`,`DATA_TYPE`
FROM `INFORMATION_SCHEMA`.`COLUMNS` 
WHERE `TABLE_SCHEMA`='rcbill' 
    AND `TABLE_NAME`='rcb_VODTITLES';
    
    SELECT `COLUMN_NAME`,`DATA_TYPE`
FROM `INFORMATION_SCHEMA`.`COLUMNS` 
WHERE `TABLE_SCHEMA`='rcbill' 
    AND `TABLE_NAME`='rcb_vodtelemetry';