use rcbill_maps;

drop table if exists IV_MOBILESITES;

CREATE TABLE `IV_MOBILESITES` (
`MOBSITEID` int not null auto_increment,
`MOBSITENO`  varchar(255) DEFAULT NULL,
`MOBSITEISLAND` varchar(255) DEFAULT NULL ,
`MOBSITENAME` varchar(255) DEFAULT NULL ,
`MOBSITETYPE` varchar(255) DEFAULT NULL ,
`MOBSITEHEIGHT` varchar(255) DEFAULT NULL ,
`MOBSITEOWNER` varchar(255) DEFAULT NULL ,
`MOBSITEPARCEL` varchar(255) DEFAULT NULL ,
`MOBSITELAT` varchar(255) DEFAULT NULL ,
`MOBSITELONG` varchar(255) DEFAULT NULL ,
`MOBSITECOORDX` varchar(255) DEFAULT NULL ,
`MOBSITECOORDY` varchar(255) DEFAULT NULL ,
`MOBSITEICON` varchar(255) DEFAULT NULL ,
`MOBSITEICONSIZE` varchar(255) DEFAULT NULL ,
`MOBSITEICONOFFSET` varchar(255) DEFAULT NULL ,
`MOBSITESTATUS` varchar(255) DEFAULT NULL ,
`COMMENT` longtext DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL, 
`MODIFIEDON` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
primary key (`MOBSITEID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- drop index IDXMS1 on IV_MOBILESITES;


CREATE INDEX IDXMS1
ON IV_MOBILESITES (MOBSITENAME);



insert into rcbill_maps.IV_MOBILESITES
(MOBSITENO, MOBSITEISLAND, MOBSITENAME, MOBSITETYPE, MOBSITEHEIGHT, MOBSITEOWNER, MOBSITEPARCEL, MOBSITELAT, MOBSITELONG, MOBSITECOORDX, MOBSITECOORDY, MOBSITEICON, MOBSITEICONSIZE, MOBSITEICONOFFSET, MOBSITESTATUS, COMMENT) 
values ('312', 'MAHE', 'La Misere', 'GBT' , '35M','GOS','B4484','-4.670381','55.473643','','','','','','Approved','DC/894/20(DC/338/20)')
;



-- select * from rcbill_maps.IV_MOBILESITES;
/*

select @@version as version;


SET SESSION sql_mode = 'ALLOW_INVALID_DATES';
SET safe_update

SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE  rcbill_maps.IV_MOBILESITES
DROP COLUMN INSERTEDON;

alter table rcbill_maps.IV_MOBILESITES
add column `INSERTEDON` datetime DEFAULT CURRENT_TIMESTAMP
;

alter table rcbill_maps.IV_MOBILESITES
add column `MODIFIEDON` datetime ON UPDATE NOW() after INSERTEDON
;

select * from rcbill_maps.IV_MOBILESITES;

CREATE TABLE rcbill_maps.IV_MOBILESITES_BKP LIKE rcbill_maps.IV_MOBILESITES;
INSERT INTO rcbill_maps.IV_MOBILESITES_BKP SELECT * FROM rcbill_maps.IV_MOBILESITES;


CREATE TABLE rcbill_maps.IV_MOBILESITES LIKE rcbill_maps.IV_MOBILESITES_BKP;
INSERT INTO rcbill_maps.IV_MOBILESITES SELECT * FROM rcbill_maps.IV_MOBILESITES_BKP;


INSERT INTO  rcbill_maps.IV_MOBILESITES(MOBSITEID, MOBSITENO, MOBSITEISLAND, MOBSITENAME, MOBSITETYPE, MOBSITEHEIGHT, MOBSITEOWNER, MOBSITEPARCEL, MOBSITELAT, MOBSITELONG, MOBSITECOORDX, MOBSITECOORDY, MOBSITEICON, MOBSITEICONSIZE, MOBSITEICONOFFSET, MOBSITESTATUS, COMMENT)
 SELECT * FROM rcbill_maps.IV_MOBILESITES_BKP;

select * from rcbill_maps.IV_MOBILESITES_BKP;

set sql_safe_updates=0;
update rcbill_maps.IV_MOBILESITES set MOBSITEICONSIZE='40,40';

update rcbill_maps.IV_MOBILESITES set insertedon='2021-06-22';

update rcbill_maps.IV_MOBILESITES set modifiedon='2021-06-22';


-- select 	"lat",	"lon",	"title",	"description",	"icon",	"iconSize",	"iconOffset"
select mobsitelat as lat, mobsitelong as lon, mobsitename as title, 
concat_ws("<BR>",MOBSITENO,MOBSITENAME,MOBSITETYPE,MOBSITEISLAND,MOBSITEOWNER,MOBSITEPARCEL,MOBSITELAT,MOBSITELONG, MOBSITECOORDX,MOBSITECOORDY,MOBSITESTATUS,COMMENT) as description
from rcbill_maps.IV_MOBILESITES
;





1	312	MAHE	LA MISERE	GBT	GOS	B4484	-4.670381	55.473643			icon/green_tower.png	30,30	-20,-20	APPROVED	DC/894/20(DC/338/20)
2	296	MAHE	ANCHOR CAFE	GBT	GOS	C10339	-4.74708	55.49331			icon/green_tower.png	30,30	-20,-20	APPROVED	DC/342/20
3	231	MAHE	PROVIDENCE	PALM	GOS	V21016	-4.649573	55.479334			icon/palm-tree.png	30,30	-20,-20	ERECTED	PALM TREE HAS BEEN ERECTED. EQUIPMENT TO BE INSTALLED
4	183	MAHE	AV BUILDING	RTP	PRIVATE (AV GROUP)	V5513	-4.62262	55.45013			icon/building1.png	30,30	-20,-20	APPROVED	WAITING FOR WMC REPORT ON WHERE TO INSTALL
5	161	MAHE	INDEPENDENCE	RTP	PRIVATE		-4.623599	55.454766			icon/building1.png	30,30	-20,-20	PENDING	WAITING
6	122	MAHE	LA BATIE	GBP	GOS		-4.605612	55.436075			icon/pole1.png	30,30	-20,-20	PENDING	PENDING
7	171	MAHE	PERSEVERANCE	GBT	AIRTEL		-4.60471	55.46204			icon/red_tower.png	30,30	-20,-20	PENDING	TEST
8	242	MAHE	ANSE FAURE	GBT	SBC		-4.683761111	55.52859444			icon/yellow_tower.png	30,30	-20,-20	PENDING	NEED TO GET PERMISSION
9	311	MAHE	BARBARONS	GBT	BBC		-4.68033	55.454			icon/black_tower.png	30,30	-20,-20	PENDING	PENDING
11	202	MAHE	STADIUM	GBT	OTHER		-4.63617	55.47109			icon/tower1.png	30,30	-20,-20	PENDING	PENDING
12	151	MAHE	MONT BUXTON	GBT	GOS	V21114	-4.612716	55.447746			icon/green_tower.png	30,30	-20,-20	APPROVED	DC/372/20
																														

*/