use rcbill_maps;

drop table if exists IV_MOBILESITES;

CREATE TABLE `IV_MOBILESITES` (
`MOBSITEID` int not null auto_increment,
`MOBSITENO`  varchar(255) DEFAULT NULL,
`MOBSITENAME` varchar(255) DEFAULT NULL ,
`MOBSITETYPE` varchar(255) DEFAULT NULL ,
`MOBSITEOWNER` varchar(255) DEFAULT NULL ,
`MOBSITEPARCEL` varchar(255) DEFAULT NULL ,
`MOBSITELAT` varchar(255) DEFAULT NULL ,
`MOBSITELONG` varchar(255) DEFAULT NULL ,
`MOBSITECOORDX` varchar(255) DEFAULT NULL ,
`MOBSITECOORDY` varchar(255) DEFAULT NULL ,
`MOBSITEICON` varchar(255) DEFAULT NULL ,
`MOBSITEICONSIZE` varchar(255) DEFAULT NULL ,
`MOBSITEICONOFFSET` varchar(255) DEFAULT NULL ,
`MOBSITESTATUS` varchar(255) DEFAULT NULL ,
`COMMENT` longtext DEFAULT NULL ,
-- ,
-- `INSERTEDON` datetime DEFAULT NULL
primary key (`MOBSITEID`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

drop index IDXMS1 on IV_MOBILESITES;


CREATE INDEX IDXMS1
ON IV_MOBILESITES (MOBSITENAME);



-- select * from rcbill_maps.IV_MOBILESITES;