use rcbill_extract;


#####################################################################
## CUSTOMER ACCOUNT
CREATE TABLE rcbill_extract.IV_CUSTOMERACCOUNT_20201219 LIKE rcbill_extract.IV_CUSTOMERACCOUNT;
INSERT INTO rcbill_extract.IV_CUSTOMERACCOUNT_20201219 SELECT * FROM rcbill_extract.IV_CUSTOMERACCOUNT;

## BILLING ACCOUNT
CREATE TABLE rcbill_extract.IV_BILLINGACCOUNT_20201219 LIKE rcbill_extract.IV_BILLINGACCOUNT;
INSERT INTO rcbill_extract.IV_BILLINGACCOUNT_20201219 SELECT * FROM rcbill_extract.IV_BILLINGACCOUNT;

## SERVICE ACCOUNT
CREATE TABLE rcbill_extract.IV_SERVICEACCOUNT_20201219 LIKE rcbill_extract.IV_SERVICEACCOUNT;
INSERT INTO rcbill_extract.IV_SERVICEACCOUNT_20201219 SELECT * FROM rcbill_extract.IV_SERVICEACCOUNT;

## SERVICE INSTANCE
CREATE TABLE rcbill_extract.IV_SERVICEINSTANCE_20201219 LIKE rcbill_extract.IV_SERVICEINSTANCE;
INSERT INTO rcbill_extract.IV_SERVICEINSTANCE_20201219 SELECT * FROM rcbill_extract.IV_SERVICEINSTANCE;

## SERVICE INSTANCE CHARGE
CREATE TABLE rcbill_extract.IV_SERVICEINSTANCECHARGE_20201219 LIKE rcbill_extract.IV_SERVICEINSTANCECHARGE;
INSERT INTO rcbill_extract.IV_SERVICEINSTANCECHARGE_20201219 SELECT * FROM rcbill_extract.IV_SERVICEINSTANCECHARGE;

## INVENTORY
CREATE TABLE rcbill_extract.IV_INVENTORY_20201219 LIKE rcbill_extract.IV_INVENTORY;
INSERT INTO rcbill_extract.IV_INVENTORY_20201219 SELECT * FROM rcbill_extract.IV_INVENTORY;

## ADDON 
CREATE TABLE rcbill_extract.IV_ADDON_20201219 LIKE rcbill_extract.IV_ADDON;
INSERT INTO rcbill_extract.IV_ADDON_20201219 SELECT * FROM rcbill_extract.IV_ADDON;

## ADDON CHARGE
CREATE TABLE rcbill_extract.IV_ADDONCHARGE_20201219 LIKE rcbill_extract.IV_ADDONCHARGE;
INSERT INTO rcbill_extract.IV_ADDONCHARGE_20201219 SELECT * FROM rcbill_extract.IV_ADDONCHARGE;

## PAYMENT HISTORY
CREATE TABLE rcbill_extract.IV_PAYMENTHISTORY_20201219 LIKE rcbill_extract.IV_PAYMENTHISTORY;
INSERT INTO rcbill_extract.IV_PAYMENTHISTORY_20201219 SELECT * FROM rcbill_extract.IV_PAYMENTHISTORY;

## BILL SUMMARY
CREATE TABLE rcbill_extract.IV_BILLSUMMARY_20201219 LIKE rcbill_extract.IV_BILLSUMMARY;
INSERT INTO rcbill_extract.IV_BILLSUMMARY_20201219 SELECT * FROM rcbill_extract.IV_BILLSUMMARY;

## BILL DETAIL
CREATE TABLE rcbill_extract.IV_BILLDETAIL_20201219 LIKE rcbill_extract.IV_BILLDETAIL;
INSERT INTO rcbill_extract.IV_BILLDETAIL_20201219 SELECT * FROM rcbill_extract.IV_BILLDETAIL;

## NBD
CREATE TABLE rcbill_extract.IV_NBD_20201219 LIKE rcbill_extract.IV_NBD;
INSERT INTO rcbill_extract.IV_NBD_20201219 SELECT * FROM rcbill_extract.IV_NBD;

## DISCOUNT
CREATE TABLE rcbill_extract.IV_DISCOUNT_20201219 LIKE rcbill_extract.IV_DISCOUNT;
INSERT INTO rcbill_extract.IV_DISCOUNT_20201219 SELECT * FROM rcbill_extract.IV_DISCOUNT;

## BALANCE
CREATE TABLE rcbill_extract.IV_BALANCE_20201219 LIKE rcbill_extract.IV_BALANCE;
INSERT INTO rcbill_extract.IV_BALANCE_20201219 SELECT * FROM rcbill_extract.IV_BALANCE;

## CREDIT NOTE
CREATE TABLE rcbill_extract.IV_CREDITNOTE_20201219 LIKE rcbill_extract.IV_CREDITNOTE;
INSERT INTO rcbill_extract.IV_CREDITNOTE_20201219 SELECT * FROM rcbill_extract.IV_CREDITNOTE;

## DEBIT NOTE
CREATE TABLE rcbill_extract.IV_DEBITNOTE_20201219 LIKE rcbill_extract.IV_DEBITNOTE;
INSERT INTO rcbill_extract.IV_DEBITNOTE_20201219 SELECT * FROM rcbill_extract.IV_DEBITNOTE;

#####################################################################