use rcbill_my;

drop table if exists dailycalls;

CREATE TABLE `dailycalls` (
`CALLDATE` datetime DEFAULT NULL ,
`CALLQUEUE` varchar(255) DEFAULT NULL ,
`CALLQUEUENAME` varchar(255) DEFAULT NULL ,
`CALLAGENT` varchar(255) DEFAULT NULL ,
`CALLNUMBER` varchar(255) DEFAULT NULL ,
`CALLEVENT` varchar(255) DEFAULT NULL ,
`CALLEVENTNAME` varchar(255) DEFAULT NULL ,
`WAITTIME` time DEFAULT NULL ,
`TALKTIME` time DEFAULT NULL ,
`UNIQUEID` bigint DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE INDEX IDXDC1
ON dailycalls (CALLAGENT);

CREATE INDEX IDXDC2
ON dailycalls (CALLNUMBER);

CREATE INDEX IDXDC3
ON dailycalls (CALLEVENT);

CREATE INDEX IDXDC4
ON dailycalls (CALLQUEUENAME);

CREATE INDEX IDXDC5
ON dailycalls (CALLEVENTNAME);


CREATE INDEX IDXDC6
ON dailycalls (CALLDATE);

CREATE INDEX IDXDC7
ON dailycalls (CALLEVENTNAME);

SHOW INDEX FROM dailycalls;