use rcbill;

drop table if exists rcb_iptv_channels;

CREATE TABLE `rcb_iptv_channels` (

`ID` int(11) DEFAULT NULL ,
`CKEY` varchar(255) DEFAULT NULL ,
`NAME` varchar(255) DEFAULT NULL ,
`CRYPTER_ID` int(11) DEFAULT NULL ,
`PCR_PID` int(11) DEFAULT NULL ,
`VIDEO_PID` int(11) DEFAULT NULL ,
`VIDEO_CODEC_ID` int(11) DEFAULT NULL ,
`ASPECT_RATIO` decimal(12,5) DEFAULT NULL ,
`STREAM_URI` varchar(255) DEFAULT NULL ,
`REQUEST_ID` int(11) DEFAULT NULL ,
`RECONNECT_REQUEST_ID` int(11) DEFAULT NULL ,
`INITIALLY_LOCKED` int(11) DEFAULT NULL ,
`ADJ_DIGITAL_CONTOUR_REDUCTION` int(11) DEFAULT NULL ,
`ADJ_MOSQUITO_NOISE_REDUCTION` int(11) DEFAULT NULL ,
`ADJ_BLOCK_NOISE_REDUCTION` int(11) DEFAULT NULL ,
`ADJ_CONTRAST` int(11) DEFAULT NULL ,
`ADJ_SATURATION` int(11) DEFAULT NULL ,
`ADJ_HUE` int(11) DEFAULT NULL ,
`ADJ_BRIGHTNESS` int(11) DEFAULT NULL ,
`ADJ_SHARPNESS` int(11) DEFAULT NULL ,
`ADJ_DEINTERLACER` int(11) DEFAULT NULL ,
`PIP_STREAM_URI` varchar(255) DEFAULT NULL ,
`PIP_VIDEO_PID` int(11) DEFAULT NULL ,
`PIP_WIDTH` int(11) DEFAULT NULL ,
`PIP_HEIGHT` int(11) DEFAULT NULL ,
`OVERLAY_PIP_DISABLED` int(11) DEFAULT NULL ,
`TS_SERVER_ID` int(11) DEFAULT NULL ,
`TS_WINDOW_DEPTH` datetime DEFAULT NULL ,
`TS_STREAM_NAME` varchar(255) DEFAULT NULL ,
`DESCRIPTION` varchar(255) DEFAULT NULL ,
`RADIO_STATION` int(11) DEFAULT NULL ,
`FORCED_ASPECT_RATIO` int(11) DEFAULT NULL ,
`IPTV_WEB_URL` int(11) DEFAULT NULL ,
`TENANT_ID` int(11) DEFAULT NULL ,
`TS_WINDOW_DEPTH_HRS` int(11) DEFAULT NULL ,
`TVSCHEDULE_SOURCE_URI` varchar(255) DEFAULT NULL ,
`TVSCHEDULE_OFFSET_IN_MINUTES` int(11) DEFAULT NULL ,
`HLS_TS_SERVER_ID` int(11) DEFAULT NULL ,
`HLS_TS_WINDOW_DEPTH_HRS` int(11) DEFAULT NULL ,
`HLS_TS_STREAM_NAME` varchar(255) DEFAULT NULL ,
`PICTUREID` int(11) DEFAULT NULL ,
`TILEID` int(11) DEFAULT NULL ,
`LINEAR_MAX_RATE_MBPS` decimal(12,5) DEFAULT NULL ,
`HLS_MAX_TOTAL_RATE_MBPS` decimal(12,5) DEFAULT NULL ,
`MULTICAST_URI` varchar(255) DEFAULT NULL ,
`HLS_URI` varchar(255) DEFAULT NULL ,
`CROP_TOP` int(11) DEFAULT NULL ,
`CROP_BOTTOM` int(11) DEFAULT NULL ,
`CROP_LEFT` int(11) DEFAULT NULL ,
`CROP_RIGHT` int(11) DEFAULT NULL ,
`CROP` int(11) DEFAULT NULL ,
`ID_OLD` int(11) DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`UPDDATE` datetime DEFAULT NULL ,
`GRESOURCEID` int(11) DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL 
) ENGINE=InnoDB DEFAULT CHARSET UTF8;


CREATE INDEX IDXic1
ON rcb_iptv_channels (`ID`);

CREATE INDEX IDXic2
ON rcb_iptv_channels (`CKEY`);

CREATE INDEX IDXic3
ON rcb_iptv_channels (`NAME`);
/*
ALTER TABLE rcb_address  
ADD FULLTEXT(settlementname, areaname, districtname);
*/