use rcbill;

drop table if exists rcb_rpdiscounts;



CREATE TABLE `rcb_rpdiscounts` (

`ID` int(11) DEFAULT NULL ,
`RATINGPLANID` int(11) DEFAULT NULL ,
`SERVICEID` int(11) DEFAULT NULL ,
`DISCOUNTTYPE` int(11) DEFAULT NULL ,
`TYPE` int(11) DEFAULT NULL ,
`DISCOUNTORDER` int(11) DEFAULT NULL ,
`DISCOUNTNAME` varchar(255) DEFAULT NULL ,
`DISCOUNT` decimal(12,5) DEFAULT NULL ,
`PRICE` decimal(12,5) DEFAULT NULL ,
`VALIDITY` int(11) DEFAULT NULL ,
`RPEXPORTCODE` varchar(255) DEFAULT NULL ,
`ID_OLD` int(11) DEFAULT NULL ,
`UPDDATE` datetime DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`ABSOLUTEVALUE` int(11) DEFAULT NULL ,


`INSERTEDON` datetime DEFAULT NULL	,
`REPORTDATE` date DEFAULT NULL	
) ENGINE=InnoDB CHARSET UTF8;

