use rcbill;

drop table if exists rcb_gatekeepers;


/*
CREATE TABLE `rcb_devicetypes` (
`id` int(11) DEFAULT NULL ,
`name` varchar(255) DEFAULT NULL ,
`ServiceTypeID` int(11) DEFAULT NULL ,
`SubDevice` int(11) DEFAULT NULL ,
`ID_OLD` int(11) DEFAULT NULL ,
`UpdDate` datetime DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL,
`REPORTDATE` date DEFAULT NULL

) ENGINE=InnoDB CHARSET UTF8;
*/

CREATE TABLE `rcb_gatekeepers`(
`ID` int(11) DEFAULT NULL ,
`NAME` varchar(255) DEFAULT NULL ,
`SERVICETYPEID` int(11) DEFAULT NULL ,
`IP` varchar(255) DEFAULT NULL ,
`PREFIX` varchar(255) DEFAULT NULL ,
`CITYPREFIX` int(11) DEFAULT NULL ,
`TFTPURL` varchar(255) DEFAULT NULL ,
`FTPURL` varchar(255) DEFAULT NULL ,
`FTPUSER` varchar(255) DEFAULT NULL ,
`FTPPASS` varchar(255) DEFAULT NULL ,
`STOREALL` int(11) DEFAULT NULL ,
`STOREALLRAD` int(11) DEFAULT NULL ,
`DISALLOWFORWARD` int(11) DEFAULT NULL ,
`LOGRETRYES` int(11) DEFAULT NULL ,
`LOCKTIME` int(11) DEFAULT NULL ,
`PINLEN` int(11) DEFAULT NULL ,
`OWNERID` int(11) DEFAULT NULL ,
`REQUIRESTATICIPADDRESS` int(11) DEFAULT NULL ,
`USESTATICIPADDRESS` int(11) DEFAULT NULL ,
`USEDDNS` int(11) DEFAULT NULL ,
`DEFAULTDOMAIN` varchar(255) DEFAULT NULL ,
`REQUIRESUBDEVICEKNOWLEDGE` int(11) DEFAULT NULL ,
`INTERIMINTERVAL` int(11) DEFAULT NULL ,
`SESSIONTIMEOUT` int(11) DEFAULT NULL ,
`INTERNALMULTILINK` int(11) DEFAULT NULL ,
`REJECTTOPOOLID` int(11) DEFAULT NULL ,
`PARENTID` int(11) DEFAULT NULL ,
`ALLOWCHILDREAUTHENTICATION` int(11) DEFAULT NULL ,
`SIMPLEAUTHENTICATION` int(11) DEFAULT NULL ,
`PROVISIONINGTYPE` varchar(255) DEFAULT NULL ,
`RADIUSMODEL` varchar(255) DEFAULT NULL ,
`REQUIREFREEDEVICE` int(11) DEFAULT NULL ,
`ID_OLD` int(11) DEFAULT NULL ,
`UPDDATE` varchar(255) DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`REJECTTOTRAFICSPEED` varchar(255) DEFAULT NULL ,
`TEMPACTIVATETOPOOLID` int(11) DEFAULT NULL ,
`TEMPACTIVATETOTRAFICSPEED` varchar(255) DEFAULT NULL ,
`USERAUTHENTICATION` int(11) DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



