use rcbill_usage;

LOAD DATA LOW_PRIORITY LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\PUC\\puc_bills_31122020-31102021.csv' 
REPLACE INTO TABLE `rcbill_usage`.`puc_bills` CHARACTER SET UTF8 FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\r\n' 
IGNORE 1 LINES 
(
@DATE ,
@METER_TYPE ,
@ISLAND ,
@METER_NAME ,
@METER_NUMBER ,
@AMOUNT ,
@UNITS ,
@NODE ,
@COMMENTS 
) 
set 
DATE=STR_TO_DATE(@DATE, '%d/%m/%Y') ,
METER_TYPE=@METER_TYPE ,
ISLAND=@ISLAND ,
METER_NAME=@METER_NAME ,
METER_NUMBER=@METER_NUMBER ,
AMOUNT=@AMOUNT ,
UNITS=@UNITS ,
NODE=@NODE ,
COMMENTS=@COMMENTS ,
INSERTEDON=now()
;


-- select * from rcbill_usage.puc_bills;

