use rcbill;

LOAD DATA LOW_PRIORITY LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\RCBill\\AllIPTVPackageChannels-09092021.csv' 
REPLACE INTO TABLE `rcbill`.`rcb_iptv_package_channels` CHARACTER SET UTF8 FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\r\n' 
IGNORE 1 LINES 
(
@ID ,
@PACKAGE_ID ,
@CHANNEL_ID ,
@ENABLED ,
@ORDER_WEIGHT ,
@CHANNEL ,
@ID_OLD ,
@UpdDate ,
@USERID ,
@ALTERNATIVE_NAME ,
@MINUTES_SHIFTED 
) 
set 
ID=@ID ,
PACKAGE_ID=@PACKAGE_ID ,
CHANNEL_ID=@CHANNEL_ID ,
ENABLED=@ENABLED ,
ORDER_WEIGHT=@ORDER_WEIGHT ,
CHANNEL=@CHANNEL ,
ID_OLD=@ID_OLD ,
UPDDATE=@UpdDate ,
USERID=@USERID ,
ALTERNATIVE_NAME=@ALTERNATIVE_NAME ,
MINUTES_SHIFTED=@MINUTES_SHIFTED ,
INSERTEDON=now()
;


-- select * from rcbill.rcb_iptv_package_channels;

