use rcbill_my;

drop table if exists rcbill_my.holidays;

CREATE TABLE `holidays` (
	`HOLIDAY_ID` INT(11) NOT NULL,
	`HOLIDAY_DATE` DATETIME NULL DEFAULT NULL,
	`WEEK_DAY` VARCHAR(12) NULL DEFAULT NULL,
	`HOLIDAY_NAME` VARCHAR(45) NULL DEFAULT NULL,
	`COUNTRY_CODE` VARCHAR(45) NOT NULL DEFAULT 'ALL',
	PRIMARY KEY (`HOLIDAY_ID`)
)
ENGINE=InnoDB DEFAULT CHARSET UTF8
;


select * from rcbill_my.holidays;

/*


INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (1,'2022-01-01 0:0:0','SATURDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (2,'2022-01-03 0:0:0','MONDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (3,'2022-04-15 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (4,'2022-04-17 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (5,'2022-04-18 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (6,'2022-05-01 0:0:0','SUNDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (7,'2022-05-02 0:0:0','MONDAY','LABOUR DAY HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (8,'2022-06-16 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (9,'2022-06-18 0:0:0','SATURDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (10,'2022-06-29 0:0:0','WEDNESDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (11,'2022-08-15 0:0:0','MONDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (12,'2022-11-01 0:0:0','TUESDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (13,'2022-12-08 0:0:0','THURSDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (14,'2022-12-25 0:0:0','SUNDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (15,'2022-12-26 0:0:0','MONDAY','CHRISTMAS HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (16,'2021-01-01 0:0:0','FRIDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (17,'2021-01-02 0:0:0','SATURDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (18,'2021-04-02 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (19,'2021-04-04 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (20,'2021-04-05 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (21,'2021-05-01 0:0:0','SATURDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (22,'2021-06-03 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (23,'2021-06-18 0:0:0','FRIDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (24,'2021-06-29 0:0:0','TUESDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (25,'2021-08-15 0:0:0','SUNDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (26,'2021-11-01 0:0:0','MONDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (27,'2021-12-08 0:0:0','WEDNESDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (28,'2021-12-25 0:0:0','SATURDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (29,'2020-01-01 0:0:0','WEDNESDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (30,'2020-01-02 0:0:0','THURSDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (31,'2020-01-03 0:0:0','FRIDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (32,'2020-04-10 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (33,'2020-04-12 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (34,'2020-04-13 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (35,'2020-05-01 0:0:0','FRIDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (36,'2020-06-11 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (37,'2020-06-18 0:0:0','THURSDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (38,'2020-06-29 0:0:0','MONDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (39,'2020-08-15 0:0:0','SATURDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (40,'2020-11-01 0:0:0','SUNDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (41,'2020-11-02 0:0:0','MONDAY','ALL SAINTS DAY HOLIDAY','');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (42,'2020-12-08 0:0:0','TUESDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (43,'2020-12-25 0:0:0','FRIDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (44,'2019-01-01 0:0:0','TUESDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (45,'2019-01-02 0:0:0','WEDNESDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (46,'2019-04-19 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (47,'2019-04-21 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (48,'2019-04-22 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (49,'2019-05-01 0:0:0','WEDNESDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (50,'2019-06-18 0:0:0','TUESDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (51,'2019-06-20 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (52,'2019-06-29 0:0:0','SATURDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (53,'2019-08-15 0:0:0','THURSDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (54,'2019-11-01 0:0:0','FRIDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (55,'2019-12-08 0:0:0','SUNDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (56,'2019-12-25 0:0:0','WEDNESDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (57,'2018-01-01 0:0:0','MONDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (58,'2018-01-02 0:0:0','TUESDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (59,'2018-03-30 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (60,'2018-04-01 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (61,'2018-04-02 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (62,'2018-05-01 0:0:0','TUESDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (63,'2018-05-31 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (64,'2018-06-18 0:0:0','MONDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (65,'2018-06-29 0:0:0','FRIDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (66,'2018-08-15 0:0:0','WEDNESDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (67,'2018-11-01 0:0:0','THURSDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (68,'2018-12-08 0:0:0','SATURDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (69,'2018-12-25 0:0:0','TUESDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (70,'2017-01-01 0:0:0','SUNDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (71,'2017-01-02 0:0:0','MONDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (72,'2017-04-14 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (73,'2017-04-16 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (74,'2017-04-17 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (75,'2017-05-01 0:0:0','MONDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (76,'2017-06-15 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (77,'2017-06-18 0:0:0','SUNDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (78,'2017-06-19 0:0:0','MONDAY','CONSTITUTION DAY HOLIDAY','');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (79,'2017-06-29 0:0:0','THURSDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (80,'2017-08-15 0:0:0','TUESDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (81,'2017-11-01 0:0:0','WEDNESDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (82,'2017-12-08 0:0:0','FRIDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (83,'2017-12-25 0:0:0','MONDAY','CHRISTMAS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (84,'2017-01-01 0:0:0','SUNDAY','NEW YEARS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (85,'2017-01-02 0:0:0','MONDAY','NEW YEAR HOLIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (86,'2017-04-14 0:0:0','FRIDAY','GOOD FRIDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (87,'2017-04-16 0:0:0','SUNDAY','EASTER SUNDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (88,'2017-04-17 0:0:0','MONDAY','EASTER MONDAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (89,'2017-05-01 0:0:0','MONDAY','LABOUR DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (90,'2017-06-15 0:0:0','THURSDAY','CORPUS CHRISTI','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (91,'2017-06-18 0:0:0','SUNDAY','CONSTITUTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (92,'2017-06-19 0:0:0','MONDAY','CONSTITUTION DAY HOLIDAY','');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (93,'2017-06-29 0:0:0','THURSDAY','INDEPENDENCE (NATIONAL) DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (94,'2017-08-15 0:0:0','TUESDAY','ASSUMPTION DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (95,'2017-11-01 0:0:0','WEDNESDAY','ALL SAINTS DAY','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (96,'2017-12-08 0:0:0','FRIDAY','IMMACULATE CONCEPTION','SC');
INSERT INTO `holidays` (`HOLIDAY_ID`, `HOLIDAY_DATE`, `WEEK_DAY`, `HOLIDAY_NAME`, `COUNTRY_CODE`) VALUES (97,'2017-12-25 0:0:0','MONDAY','CHRISTMAS DAY','SC');


*/