
LOAD DATA LOW_PRIORITY LOCAL INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 5.7\\Uploads\\OtherImport\\AccommodationAndCatering_Clean_01062017.csv' 
REPLACE INTO TABLE `rcbill_my`.`establishment` CHARACTER SET UTF8 FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '\r\n' 
IGNORE 1 LINES 
(
@ESTID ,
@ESTNAME ,
@ESTMANAGER ,
@ESTADDRESS ,
@ESTLOCATION ,
@ESTISLAND ,
@ESTPHONE ,
@ESTFAX ,
@ESTEMAIL ,
@ESTWEBSITE ,
@ESTSTATUS ,
@ESTLICENSETYPE ,
@ESTREMARK ,
@ESTROOMS ,
@ESTBEDS ,
@ESTRESTAURANTS ,
@ESTRESTNAME ,
@ESTCOVERS 
) 
set 

-- ESTID=@ESTID ,
ESTNAME=upper(trim(@ESTNAME)) ,
ESTMANAGER=upper(trim(@ESTMANAGER)) ,
ESTADDRESS=upper(trim(@ESTADDRESS)) ,
ESTLOCATION=upper(trim(@ESTLOCATION)) ,
ESTISLAND=upper(trim(@ESTISLAND)) ,
ESTPHONE=@ESTPHONE ,
ESTFAX=@ESTFAX ,
ESTEMAIL=@ESTEMAIL ,
ESTWEBSITE=@ESTWEBSITE ,
ESTSTATUS=upper(trim(@ESTSTATUS)) ,
ESTLICENSETYPE=upper(trim(@ESTLICENSETYPE)) ,
ESTREMARK=@ESTREMARK ,
ESTROOMS=@ESTROOMS ,
ESTBEDS=@ESTBEDS ,
ESTRESTAURANTS=@ESTRESTAURANTS ,
ESTRESTNAME=@ESTRESTNAME ,
ESTCOVERS=@ESTCOVERS ,
INSERTEDON=now()
;



-- select * from establishment;

/*
select distinct estlicensetype, estrooms, count(*) from establishment 
group by estlicensetype, estrooms
;
*/

#Load phone details in different table
DROP TABLE IF EXISTS rcbill_my.establishmentphones;
        
create table rcbill_my.establishmentphones as 
(
SELECT t.ESTID, t.ESTNAME, t.ESTMANAGER, t.ESTROOMS, t.ESTLOCATION, trim(SUBSTRING_INDEX(SUBSTRING_INDEX(t.ESTPHONE, '/', n.n), '/', -1)) as ESTPHONE
  FROM rcbill_my.establishment t CROSS JOIN 
(
   SELECT a.N + b.N * 10 + 1 n
     FROM 
    (SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
   ,(SELECT 0 AS N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    ORDER BY n
) n
 WHERE n.n <= 1 + (LENGTH(t.ESTPHONE) - LENGTH(REPLACE(t.ESTPHONE, '/', '')))
 ORDER BY ESTID
);

CREATE INDEX IDXephone1
ON rcbill_my.establishmentphones (ESTPHONE);

select * from rcbill_my.establishmentphones;