use rcbill;

drop table if exists rcb_ticketclosereasons;

CREATE TABLE `rcb_ticketclosereasons` (
`TCRID` int(11) DEFAULT NULL ,
`KOD` int(11) DEFAULT NULL ,
`CLOSEREASONNAME` varchar(255) DEFAULT NULL ,
`TECHSERVICEID` int(11) DEFAULT NULL ,
`TECHLEVELID` int(11) DEFAULT NULL ,
`TICKETCLOSEREASONTYPEID` int(11) DEFAULT NULL ,
`TICKETTYPEID` int(11) DEFAULT NULL ,
`ID_OLD` int(11) DEFAULT NULL ,
`UPDDATE` datetime DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`SUCCESS` int(11) DEFAULT NULL ,
`ACTIVE` int(11) DEFAULT NULL ,
`INSERTEDON` datetime DEFAULT NULL
-- 	,
-- `REPORTDATE` date DEFAULT NULL	
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
