use rcbill;

drop table if exists rcb_tickets;


CREATE TABLE `rcb_tickets` (
`ID` int(11) DEFAULT NULL ,
`OPENDATE` datetime DEFAULT NULL ,
`OPENUSERID` int(11) DEFAULT NULL ,
`OPENREASONID` int(11) DEFAULT NULL ,
`TECHDEPTID` int(11) DEFAULT NULL ,
`TECHREGIONID` int(11) DEFAULT NULL ,
`TECHGROUPID` int(11) DEFAULT NULL ,
`VISITDATE` datetime DEFAULT NULL ,
`STAGETECHREGIONID` int(11) DEFAULT NULL ,
`EXECUTEDDATE` datetime DEFAULT NULL ,
`CLOSEDATE` datetime DEFAULT NULL ,
`CLOSEUSERID` int(11) DEFAULT NULL ,
`CLOSEREASONID` int(11) DEFAULT NULL ,
`CLOSETECHDEPTID` int(11) DEFAULT NULL ,
`CLOSETECHREGIONID` int(11) DEFAULT NULL ,
`CLOSETECHGROUPID` int(11) DEFAULT NULL ,
`CLID` int(11) DEFAULT NULL ,
`CID` int(11) DEFAULT NULL ,
`DEVID` int(11) DEFAULT NULL ,
`SEVERITYID` int(11) DEFAULT NULL ,
`SERVICEID` int(11) DEFAULT NULL ,
`TYPEID` int(11) DEFAULT NULL ,
`TYPE` varchar(255) DEFAULT NULL ,
`STATE` varchar(255) DEFAULT NULL ,
`VISITCOUNT` int(11) DEFAULT NULL ,
`WORKTIME` decimal(12,5) DEFAULT NULL ,
`SUBJECT` varchar(255) DEFAULT NULL ,
`DEVICESTATE` varchar(255) DEFAULT NULL ,
`ID_OLD` varchar(255) DEFAULT NULL ,
`UPDDATE` datetime DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`NAS` varchar(255) DEFAULT NULL ,
`PARENTID` int(11) DEFAULT NULL ,
`INTERFACE` varchar(255) DEFAULT NULL ,
`TESTDATE` datetime DEFAULT NULL ,
`TESTSTATE` varchar(255) DEFAULT NULL ,
`ACTIVITYID` int(11) DEFAULT NULL ,
`GLOBALTICKET` int(11) DEFAULT NULL ,

`INSERTEDON` datetime DEFAULT NULL	,
`REPORTDATE` date DEFAULT NULL	
) ENGINE=InnoDB CHARSET UTF8;



-- drop index IDXinvoiceheader on rcb_tickets;

