use rcbill;

drop table if exists rcb_contractdiscounts;



CREATE TABLE `rcb_contractdiscounts` (

`ID` int(11) DEFAULT NULL ,
`CID` int(11) DEFAULT NULL ,
`DISCTYPE` int(11) DEFAULT NULL ,
`TYPEID` int(11) DEFAULT NULL ,
`TYPEID1` int(11) DEFAULT NULL ,
`TYPEID2` int(11) DEFAULT NULL ,
`TYPEID3` int(11) DEFAULT NULL ,
`PERCENT` decimal(12,5) DEFAULT NULL ,
`AMOUNT` decimal(12,5) DEFAULT NULL ,
`ID_OLD` varchar(255) DEFAULT NULL ,
`UPDDATE` datetime DEFAULT NULL ,
`USERID` int(11) DEFAULT NULL ,
`APPROVED` int(11) DEFAULT NULL ,
`APPROVEDBY` int(11) DEFAULT NULL ,
`APPROVEDTS` datetime DEFAULT NULL ,
`APPROVALREASON` varchar(255) DEFAULT NULL ,

`CONTRACTCODE` varchar(255) DEFAULT NULL ,
`CLIENTCODE` varchar(255) DEFAULT NULL ,

`INSERTEDON` datetime DEFAULT NULL	,
`REPORTDATE` date DEFAULT NULL	
) ENGINE=InnoDB CHARSET UTF8;

