insert	into	`rcbill_my`.	`iv_budget`	(	`B_VERSION`	,	`B_YEAR`	,	`B_MONTH`	,	`B_REGION`	,	`B_NETWORK`	,	`B_SERVICE`	,	`B_CATEGORY`	,	`B_CLIENTCLASS`	,	`B_CONTRACTCLASS`	,	`B_PACKAGE`	,	`B_COUNT`	,	`B_REVENUEGENERATING`	,	`INSERTEDON`	)	values

	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4096	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4106	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4105	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4086	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4075	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4065	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4054	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4040	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4030	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4021	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4011	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Basic'	,	4002.274804	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	983.79	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	996.4321	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1000.947779	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1203.441874	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1208.049456	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1212.610961	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1220.126851	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1222.567583	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1222.983907	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1224.977318	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1225.369545	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Executive'	,	1232.757849	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	336	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	333	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	330	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prestige'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6292	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6332	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6366	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6555	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6672	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6755	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6819	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6868	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6885	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6913	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6936	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance'	,	6983	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1120	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1130	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1135	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1138	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extravagance Corporate'	,	1141	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	893	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	896	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	901	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	907	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	908	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	916	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	926	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	939	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	943	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	955	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	959	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian'	,	964	,	1	,	now()	)	,
    
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Indian Corporate'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	403	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	405	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	407	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	408	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	410	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	410	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	410	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	410	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	411	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	412	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	413	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'French'	,	414	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2280	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2278	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2277	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2275	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2273	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2271	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2270	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2268	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2266	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2265	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2263	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intelenovela'	,	2261	,	1	,	now()	)	,
																												
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	162	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	170	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	174	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	178	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	186	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	194	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	198	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	202	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	206	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	206	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	210	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'TurquoiseTV'	,	218	,	1	,	now()	)	,
																												
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Channels'	,	135	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'TV'	,	'Active Numbers'	,	'All'	,	'All'	,	'Hotels/Decoder'	,	145	,	1	,	now()	)	,


	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	236	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	219	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	203	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	187	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	172	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	156	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	141	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	127	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	112	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	98	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	85	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Data 10'	,	71	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	4705	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	4868	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5041	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5174	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5309	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5442	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5597	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5724	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5838	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	5955	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	6059	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson'	,	6172	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	446	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	491	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	540	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	588	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	631	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	676	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	726	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	771	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	809	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	846	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	883	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber'	,	914	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	33	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	33	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	31	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	30	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	30	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	29	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	29	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	28	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	28	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Starter'	,	27	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	717	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	720	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	718	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	719	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	733	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	734	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	742	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	745	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	746	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	748	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	749	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Value'	,	756	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1347	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1361	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1374	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1402	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1468	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1469	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1475	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1476	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1463	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1450	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1423	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Elite'	,	1421	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	810	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	793	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	778	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	767	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	757	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	745	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	740	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	732	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	713	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	700	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	688	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme'	,	675	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	171	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	161	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	151	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	141	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	132	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	122	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	112	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	104	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	95	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	87	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	78	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Extreme Plus'	,	71	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	21	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	22	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	21	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	22	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	22	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	23	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	23	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	23	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	23	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	24	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	24	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance'	,	23	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	14	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	14	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	15	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	15	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Performance Plus'	,	17	,	1	,	now()	)	,
																												
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-1'	,	32	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-2'	,	17	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-6'	,	13	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8'	,	16	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Business Unlimited-8-daytime'	,	4	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise Low Tide'	,	7	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	13	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	15	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	16	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	17	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	19	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	21	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	22	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	23	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	24	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	24	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	25	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Turquoise High Tide'	,	27	,	1	,	now()	)	,

	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Plus'	,	2	,	1	,	now()	)	,

																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Dedicated Custom'	,	108	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'PBX'	,	9	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.88	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.7624	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.647152	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.53420896	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.42352478	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.31505429	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.2087532	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.10457814	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	71.00248657	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	70.90243684	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	70.8043881	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'VPN'	,	70.70830034	,	1	,	now()	)	,
																												
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'10GB'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'20GB'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'40GB'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	209	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	211	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	213	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	215	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	217	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	219	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	221	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	223	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	225	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	227	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	229	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Crimson Corporate'	,	231	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Internet'	,	'Active Numbers'	,	'All'	,	'All'	,	'Amber Corporate'	,	9	,	1	,	now()	)	,


	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	476	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	478	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	480	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	482	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	484	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	486	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	488	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	490	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	492	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	494	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	496	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 10'	,	499	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	40	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Intel Voice 20'	,	39	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Prepaid Voice 10'	,	0	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	164	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	164	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	165	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	165	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	165	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	165	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	166	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	166	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	166	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	166	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	166	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'Voice'	,	'Active Numbers'	,	'All'	,	'All'	,	'Voice Plus'	,	167	,	1	,	now()	)	,

	(	2	,	2019	,	1	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	271	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	305	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	340	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	380	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	419	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	465	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	509	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	554	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	597	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	640	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	680	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'DualView'	,	680	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	438	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	540	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	640	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	740	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	838	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	969	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1100	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1230	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1347	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1463	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1578	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'VOD'	,	1578	,	1	,	now()	)	,
																												
	(	2	,	2019	,	1	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	2	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	3	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	4	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	5	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	6	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	7	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	8	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	9	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	10	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	11	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	,
	(	2	,	2019	,	12	,	'All'	,	'All'	,	'OTT'	,	'Active Numbers'	,	'All'	,	'All'	,	'MultiView'	,	0	,	1	,	now()	)	

;
                
                
                
                
                
select * from rcbill_my.iv_budget;

/*
set sql_safe_updates=0;
delete from rcbill_my.iv_budget where date(insertedon)='2019-02-20'
;
*/

/*
select B_MONTH, B_PACKAGE,  sum(B_COUNT) as B_COUNT from rcbill_my.iv_budget
where B_PACKAGE='Amber' and B_CATEGORY='Active Numbers'
group by B_MONTH, B_PACKAGE
-- with rollup
;


select B_MONTH, B_PACKAGE,  sum(B_COUNT) as B_COUNT from rcbill_my.iv_budget
where B_PACKAGE='Amber' and B_CATEGORY='New Sales'
group by B_MONTH, B_PACKAGE
with rollup
;

*/


select B_MONTH, B_PACKAGE,  sum(B_COUNT) as B_COUNT from rcbill_my.iv_budget
where 
0=0
and date(INSERTEDON) = (select date(max(INSERTEDON)) from rcbill_my.iv_budget)

and B_PACKAGE='Extravagance' 
and B_CATEGORY='Active Numbers'
-- and B_REGION='Praslin'
and B_REVENUEGENERATING=1
-- and B_CLIENTCLASS not in ('OTHER')
group by B_MONTH, B_PACKAGE
-- with rollup
;